add async test client (GSI-99)
ghga-de/ghga-service-commons pull request #8
Opened 2023-04-27 15:07 UTC by KerstenBreuer

```
Test client for ASGI apps that can be used in context of a running event loop.
```

2023-04-27 15:57 UTC, Cito requested changes

2023-04-27 15:57 UTC, Cito commented on ghga_service_commons/api/testing.py
> +    assert response.status == 200
```suggestion
    assert response.status_code == 200
```

2023-04-27 15:57 UTC, Cito commented on ghga_service_commons/api/testing.py
> +    assert response.content == "Hello World"
```suggestion
    assert response.json() == "Hello World"
```

Alternatively,
```py
assert response.content== b'"Hello World"'
assert response.text == '"Hello World"'
```

2023-04-27 15:57 UTC, Cito commented on ghga_service_commons/api/testing.py
> +        port = get_free_port()
But then this AsyncTestClient does not really bring and added value over the httpx.AsyncClient.

2023-05-02 08:18 UTC, KerstenBreuer commented on ghga_service_commons/api/testing.py
> +        port = get_free_port()
I thought so, too, but without the port, it did not work for both the upload controller service and metldata. Maybe we should investigate that at some point. Should I put this onto the refactoring list or do you have an immediate idea?

2023-05-02 10:19 UTC, KerstenBreuer commented on ghga_service_commons/api/testing.py
> +        port = get_free_port()
Yes, exactly. It is this test that is failing if you don't specify a base_url: https://github.com/ghga-de/metldata/blob/feature/artifacts_rest_GSI-30/tests/artifact_rest/test_api_factory.py#L97

I could confirm, however, that it is not essential to pick a free port. I changed the PR accordingly. However, the ability to pick a free port is still relevant and is needed elsewhere for the implementation of testcontainers. So keeping it here might still be worth it.

Thanks for pointing that out.

2023-05-02 10:23 UTC, Cito approved these changes

2023-05-02 10:30 UTC, merged